spring:
  profiles:
    active: local, oauth2, jwt

  messages:
    encoding: utf-8
    cache-duration: 3600
    fallback-to-system-locale: true
    basename: i18n/common/messages,
      i18n/member/messages,
      i18n/auth/messages
