server:
  port: 9000

spring:

  messages:
    encoding: utf-8
    cache-duration: 3600
    fallback-to-system-locale: true
    basename: i18n/common/messages,
      i18n/member/messages

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myalbum
    username: postgres
    password: 1234

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: { google-client-id }
            client-secret: { google-client-secret }
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/login/oauth2/code/{registrationId}"
          kakao:
            client-name: kakao
            client-id: { kakao-client-id }
            client-secret: { kakao-client-secret }
            scope:
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post # 토큰 요청 시 POST 방식 사용 (공식 문서 참고)
          naver:
            client-name: naver
            client-id: { naver-client-id }
            client-secret: { naver-client-secret }
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/login/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
